server:
  port: 8082
  servlet:
    context-path: /notification
spring:
  application:
    name: notification-service
  data:
    mongodb:
      uri: mongodb://root:root@localhost:27017/notification-service?authSource=admin
  kafka:
    bootstrap-servers: localhost:9094
    consumer:
      group-id: notification-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
notification:
  email:
    brevo-url: https://api.brevo.com
    brevo-apikey: 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
