server:
  port: 8080
  servlet:
    context-path: /identity

spring:
  application:
    name: identity-service
  datasource:
    url: "jdbc:mysql://localhost:3306/bookteria_identity"
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  kafka:
    bootstrap-servers: localhost:9094
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
jwt:
  signerKey: ${JWT_SIGNER_KEY}
  valid-duration: ${JWT_VALID_DURATION:3600} # in second
  refreshable-duration: ${JWT_REFRESHABLE_DURATION:36000} # in seconds

app:
  services:
    profile: http://localhost:8081/profile